# Generated by Django 4.0.5 on 2022-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBase',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_weight', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
