# Generated by Django 4.0.5 on 2022-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedStocks',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=255)),
                ('min_stock', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['med_id'],
            },
        ),
        migrations.AddField(
            model_name='medicinebase',
            name='medicine_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='medicinebase',
            name='minimum_stock',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
