# Generated by Django 4.0.5 on 2022-07-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medstocks_medicinebase_medicine_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medstocks',
            old_name='med_name',
            new_name='medicine_name',
        ),
        migrations.RenameField(
            model_name='medstocks',
            old_name='min_stock',
            new_name='minimum_stock',
        ),
    ]
