# Generated by Django 4.0.5 on 2022-07-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicinebase_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinebase',
            options={'ordering': ['created_at']},
        ),
    ]
