# Generated by Django 4.0.5 on 2022-07-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_medicinebase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinebase',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='medicinebase',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
