# Generated by Django 4.0.5 on 2022-07-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_med_name_medstocks_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medstocks',
            options={'ordering': ['m_id']},
        ),
        migrations.RenameField(
            model_name='medstocks',
            old_name='med_id',
            new_name='m_id',
        ),
    ]
