# Generated by Django 4.0.5 on 2022-11-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_medstocks_options_rename_med_id_medstocks_m_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medstocks',
            name='minimum_stock',
        ),
    ]
